name: wavnote
description: "Voice memo app for ios"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  flutter_sound: ^9.28.0
  just_audio: ^0.10.4
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  audio_waveforms: ^1.3.0
  mockito: ^5.4.6
  dartz: ^0.10.1
  equatable: ^2.0.7
  permission_handler: ^12.0.0+1
  fluttericon: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

